Key filter
threathunters-io/laurel pull request #90
Opened 2022-08-11 08:30 UTC by Hublerho

This PR should implement the feature to use key based filtering of auditd events.
Specifying keys in laurel.conf:

[filter]
filter-keys = ["filter-this"]

#24 Currently it only drops the whole message

Looking forward for your feedback

2022-08-11 12:16 UTC, hillu commented
Thank you for your PR!

Could you please rework your commit series so that there are at most a handful of self-contained, linear commits to review?

The `pub filter: bool` you added to the `Coalesce` object should really be part of the `Event`.

2022-08-19 06:41 UTC, Hublerho commented
Hi,
I reworked the series and added the `filter: bool` to the event.
Assuming an event should not be filtered upon creation the default is set to false.
Only while processing the value will be set accordingly.

I hope this resolves part of the issue.
Excited to hear from you!

2022-08-19 15:17 UTC, hillu requested changes
The core of your changes look okay now. There are only a few minor issues I'd like to be changed, after that I'd be happy to accept the PR.

Please put formatting-only changes into a separate commit. They distract from the actual functionality you added.

2022-08-19 15:17 UTC, hillu commented on src/config.rs
> +directory = "/etc/laurel/config.toml"
I think there's a misconception here. directory is meant to be the the "working directory", i.e. the base directory for log files.

2022-08-19 15:17 UTC, hillu commented on src/config.rs
> +        assert_eq!(c.directory, Some(Path::new("/etc/laurel/config.toml").to_path_buf()));
see above

2022-08-19 15:17 UTC, hillu commented on src/config.rs
> +        let config_file = fs::read_to_string("/etc/laurel/config.toml");
This is the line that broke the CI test.

If you feel it's necessary to parse content from a file, please include it in the `testdata` subdirectory. Most likely, howver, you should be able to get away with parsing from an inline string (see `simple` test).

2022-08-19 15:17 UTC, hillu commented on src/main.rs
> +    print!("{:?}",config.filter.filter_keys);
The `println!` looks like debug output that you forgot to strip.

2022-08-19 15:17 UTC, hillu commented on src/coalesce.rs
> +
Format-only changes should go into a separate commit.

2022-08-19 16:14 UTC, hillu commented
btw, would you also like to do the the `filter.filter-labels` feature (as discussed in #24)?

2022-08-23 12:15 UTC, Hublerho commented
I reworked/cleaned up the commits, sorry for the mess a lot of the code was due to improper cleanup before commiting (debug code).
Hope it is ok now, otherwise I am happy to correct more :D

2022-08-23 12:19 UTC, Hublerho commented
#24 sounds interesting, I can give it a try

2022-08-23 19:50 UTC, hillu commented
After rebasing onto `master` and squashing "Test implementation" and "Cleanup", I have pushed your changes.

Thank you very much for your contribution!

How would you like to be credited in the next release notes?

2022-08-23 19:50 UTC, closed without merging

2022-08-24 13:00 UTC, Hublerho commented
Great, thank you!

You can just tag me along with the feature if this is ok?